### ISSUE TITLE
Empty lines crashes the lib. 

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [ataztech910/notion-to-html#12]
Hello there,
Having empty paragraph is crashing the lib.

**Comment by ataztech910** [comment]
On my way to fix it! Thanks!

**Comment by ataztech910** [comment]
fixed in bugfix/NOTION-TO-HTML-#12, expect publish soon

**Comment by ataztech910** [comment]
resolved in version 0.1.1
